version: '2'
services:
  tribeca:
    build:
      context: ./
    image: tribeca
    env_file:
      - ./env
    links:
      - tribeca-mongo
    ports:
      - "3000:3000"
    tty: true
    volumes: 
      - data:/data
  tribeca-mongo:
    image: mongo
    restart: on-failure
    volumes:
      - data:/data/db
volumes:
  data:
    external: true